// Code generated by GenAI for parsing

#ifndef ARGPARSE_HPP
#define ARGPARSE_HPP

#include <string>
#include <iostream>
#include <cstdlib>
#include <getopt.h>


struct Config {
    std::string intf_name;
    unsigned num_cores = 1;
    unsigned queue_size = 5;
    unsigned buffer_pool_size = 1024;
};

void printUsage(const char* prog){
    std::cerr <<
        "Usage: " << prog << " -i <interface> [-c <num_cores>] [-q <queue_size>] [-b <buffer_pool_size>]\n"
        "  -i <name>   Network interface to bind (required)\n"
        "  -c <n>      Number of Core threads (default: 1)\n"
        "  -q <n>      RX/TX queue size (default: 5)\n"
        "  -b <n>      Buffer pool size (default: 1024)\n"
        "  -h          Show this message\n";
}

unsigned parsePositiveInt(const char* s, const char* flag){
    char* end = nullptr;
    long v = std::strtol(s, &end, 10);
    if (end == s || *end != '\0' || v <= 0) {
        std::cerr << "Invalid " << flag << " value: " << s << "\n";
        std::exit(EXIT_FAILURE);
    }
    return static_cast<unsigned>(v);
}

Config parseArgs(int argc, char** argv){
    Config cfg;
    bool have_interface = false;

    int opt;
    while ((opt = getopt(argc, argv, "i:c:q:b:h")) != -1) {
        switch (opt) {
            case 'i':
                cfg.intf_name = optarg;
                have_interface = true;
                break;
            case 'c':
                cfg.num_cores = parsePositiveInt(optarg, "-c");
                break;
            case 'q':
                cfg.queue_size = parsePositiveInt(optarg, "-q");
                break;
            case 'b':
                cfg.buffer_pool_size = parsePositiveInt(optarg, "-b");
                break;
            case 'h':
                printUsage(argv[0]);
                std::exit(EXIT_SUCCESS);
            default:
                printUsage(argv[0]);
                std::exit(EXIT_FAILURE);
        }
    }

    if (!have_interface) {
        std::cerr << "Error: -i is required\n";
        printUsage(argv[0]);
        std::exit(EXIT_FAILURE);
    }
    return cfg;
}

#endif